---
-  name: Ensure user is {{ state }}
   os_user:
     auth:
       auth_url: "{{ os_auth }}"
       username: "{{ cloud_admin }}"
       password: "{{ admin_password }}"
       project_name: "{{ admin_project }}"
     domain: "{{ domain_id }}"
     state: "{{ state }}"
     endpoint_type: admin
     name: "{{ item.username }}"
     password: "{{ item.password }}"
     validate_certs: False
   environment:
     OS_IDENTITY_API_VERSION: 3
     OS_PROJECT_DOMAIN_NAME: Default
     OS_USER_DOMAIN_NAME: Default
   tags: user
   with_items:
     - "{{ users.list }}"


