---



- name: scp instackenv to each undercloud
  command: >
    scp -o BatchMode=yes -o StrictHostKeyChecking=no
    files/instackenv/{{item.item.username}}-instackenv.json
    stack@{{item.ansible_facts.openstack_servers.0.public_v4}}:~/instackenv.yaml
  with_items: "{{undercloud.results}}"
  tags:
    - undercloud


