---



  - name: Add rules for icmp - ping
    os_security_group_rule:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ item[0].username }}"
         password: "{{ item[0].password }}"
         project_name: "{{ item[0].username }}-{{ item[1] }}"
         domain_id: "{{ domain_id }}"
       security_group: default
       protocol: icmp
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False
    with_nested:
      - "{{ users.list }}"
      - "{{ Projects }}"



  - name: Add rules for tcp port 22
    os_security_group_rule:
       auth:
         auth_url: "{{ os_auth }}"
         username: "{{ item[0].username }}"
         password: "{{ item[0].password }}"
         project_name: "{{ item[0].username }}-{{ item[1] }}"
         domain_id: "{{ domain_id }}"
       security_group: default
       protocol: tcp
       port_range_min: 22
       port_range_max: 22
       remote_ip_prefix: 0.0.0.0/0
       validate_certs: False
    with_nested:
      - "{{ users.list }}"
      - "{{ Projects }}"


